# Bloggo API

The API of the Bloggo service.
TODO: Finish the blueprint
TODO: Show necessary authentication headers in API blueprint

## /posts

### Get all posts [GET]

This path returns the list of all of the blog posts currently stored in the database

+ Request

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    An array of blog posts

    + Attributes (array[BlogPost])
